/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AddToCartBar`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/meatAndAddOnSelection`; params?: Router.UnknownInputParams; } | { pathname: `/menuDetails1`; params?: Router.UnknownInputParams; } | { pathname: `/SuccessfullyAdded`; params?: Router.UnknownInputParams; } | { pathname: `/_layout_`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bill` | `/bill`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orderStatus` | `/orderStatus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/que` | `/que`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AddToCartBar`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/meatAndAddOnSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/menuDetails1`; params?: Router.UnknownOutputParams; } | { pathname: `/SuccessfullyAdded`; params?: Router.UnknownOutputParams; } | { pathname: `/_layout_`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bill` | `/bill`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orderStatus` | `/orderStatus`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/que` | `/que`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/AddToCartBar${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/meatAndAddOnSelection${`?${string}` | `#${string}` | ''}` | `/menuDetails1${`?${string}` | `#${string}` | ''}` | `/SuccessfullyAdded${`?${string}` | `#${string}` | ''}` | `/_layout_${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bill${`?${string}` | `#${string}` | ''}` | `/bill${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/menu${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orderStatus${`?${string}` | `#${string}` | ''}` | `/orderStatus${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/que${`?${string}` | `#${string}` | ''}` | `/que${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AddToCartBar`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/meatAndAddOnSelection`; params?: Router.UnknownInputParams; } | { pathname: `/menuDetails1`; params?: Router.UnknownInputParams; } | { pathname: `/SuccessfullyAdded`; params?: Router.UnknownInputParams; } | { pathname: `/_layout_`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bill` | `/bill`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/menu` | `/menu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orderStatus` | `/orderStatus`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/que` | `/que`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
